spring:
  datasource:
    #OR append `?currentSchema=addsowner`
    url: jdbc:oracle:thin:@kwalxorclq02b.qa.finra.org:1521:Scrcq
    username: scrcadmin
    password: pskjf927

hive:
  url: rcemr.qc.aws.finra.org
  username: rcapp
  password: QGRob2NRdWVyeSRlcnZlcg==