spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    properties:
      hibernate:
        default_schema: scrcowner
        dialect: org.hibernate.dialect.Oracle10gDialect
        format_sql: false
        show_sql: false
        jdbc:
          batch_size: 50